export const conditions: { [key: string]: string } = {
  'clear-day': 'assets/images/clear-day.png',
  'clear-night': 'assets/images/clear-night.png',
  cloudy: 'assets/images/cloudy.png',
  fog: 'assets/images/fog.png',
  hail: 'assets/images/hail.png',
  'partly-cloudy-day': 'assets/images/partly-cloudy-day.png',
  'partly-cloudy-night': 'assets/images/partly-cloudy-night.png',
  'rain-snow-showers-day': 'assets/images/rain-snow-showers-day.png',
  'rain-snow-showers-night': 'assets/images/rain-snow-showers-night.png',
  rain: 'assets/images/rain.png',
  'showers-day': 'assets/images/showers-day.png',
  'showers-night': 'assets/images/showers-night.png',
  sleet: 'assets/images/sleet.png',
  'snow-showers-day': 'assets/images/snow-showers-day.png',
  'snow-showers-night': 'assets/images/snow-showers-night.png',
  snow: 'assets/images/snow.png',
  'thunder-rain': 'assets/images/thunder-rain.png',
  'thunder-showers-day': 'assets/images/thunder-showers-day.png',
  'thunder-showers-night': 'assets/images/thunder-showers-night.png',
  thunder: 'assets/images/thunder.png',
  wind: 'assets/images/wind.png',
};
