export const conditions: { [key: string]: string } = {
  'clear-day': 'assets/clear-day.png',
  'clear-night': 'assets/clear-night.png',
  cloudy: 'assets/cloudy.png',
  fog: 'assets/fog.png',
  hail: 'assets/hail.png',
  'partly-cloudy-day': 'assets/partly-cloudy-day.png',
  'partly-cloudy-night': 'assets/partly-cloudy-night.png',
  'rain-snow-showers-day': 'assets/rain-snow-showers-day.png',
  'rain-snow-showers-night': 'assets/rain-snow-showers-night.png',
  rain: 'assets/rain.png',
  'showers-day': 'assets/showers-day.png',
  'showers-night': 'assets/showers-night.png',
  sleet: 'assets/sleet.png',
  'snow-showers-day': 'assets/snow-showers-day.png',
  'snow-showers-night': 'assets/snow-showers-night.png',
  snow: 'assets/snow.png',
  'thunder-rain': 'assets/thunder-rain.png',
  'thunder-showers-day': 'assets/thunder-showers-day.png',
  'thunder-showers-night': 'assets/thunder-showers-night.png',
  thunder: 'assets/thunder.png',
  wind: 'assets/wind.png',
};
